framework:
    notifier:
        chatter_transports:
            windows: 'notifications'
        channel_policy:
            # use chat/slack, chat/telegram, or windows
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
