security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    

    providers:
        in_memory:
            memory:
                # Utilisateurs avec leurs rôles
                users:
                    admin:
                        password: '$2a$10$gNympqLxzCRbuHm1U.si4.XMAON0bTWQ0ihp9/gitqJ430oe7.ycq' # Mot de passe hashé pour "admin"
                        roles: ['admin']
                    citoyen:
                        password: '$2a$10$OmP5p8i3CBf3Erj5MN64weT2fN7KHimrt8NIseXAkSOFoDHmJ/UvC' # Mot de passe hashé pour "citoyen"
                        roles: ['citoyen']
                    agent:
                        password: '$2a$10$9zfb.PmhVNQx5rJ/o/viauC3kEH601b1XMfcM41UWQMKJ8sr3ZwIa' # Mot de passe hashé pour "agent"
                        roles: ['agent']

    # Configuration des pare-feux
    firewalls:
        # Configuration du pare-feu principal
        main:
            provider: in_memory # Utilisation du fournisseur d'utilisateurs en mémoire
            # Autres configurations du pare-feu principal...
            # Par exemple, configurer le système d'authentification (form_login, etc.)
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login

    # Activation de la sécurité pour différentes parties de l'application
    access_control:
        # Exemple d'accès restreint à certaines URL en fonction des rôles
        - { path: ^/admin, roles: admin } # Accès restreint aux utilisateurs avec le rôle "ROLE_ADMIN"
        - { path: ^/citoyen, roles: citoyen } # Accès restreint aux utilisateurs avec le rôle "ROLE_CITOYEN"
        - { path: ^/agent, roles: agent } # Accès restreint aux utilisateurs avec le rôle "ROLE_AGENT"
        # Autres configurations d'accès restreint...

