vich_uploader:
    db_driver: orm
    mappings:
        ressources_images: 
            uri_prefix: /images/ressources
            upload_destination: '%kernel.project_dir%/public/images/ressources'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
