#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods: ['GET']
