# config/routes.yaml

app_solutions_autocomplete:
  path: /solutions/autocomplete
  controller: 'App\Controller\SolutionsController::autocomplete'
  methods: [GET]

# Define your existing routes below
index:
  path: /
  controller: App\Controller\DefaultController::index
